name: Security - Bandit

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install bandit; fi

      - name: Run Bandit (recursive)
        run: |
          mkdir -p reports
          bandit -r . -c bandit.yaml -f json -o reports/bandit-report.json || true
          bandit -r . -c bandit.yaml -f txt -o reports/bandit-report.txt || true

      - name: Upload Bandit reports
        uses: actions/upload-artifact@v4
        with:
          name: bandit-reports
          path: reports/
          if-no-files-found: error
